//Print Greek Words 

public class PrintGreekWords {
    public static void main(String[] args) {
        char i;
        char x = 0x0370;
        char y = 0x03ff;
        for(i = x; i<=y;i++){

            System.out.println("The Symbol is :  "+i);
        }
    }
}

/*
The Symbol is :  Ͱ
The Symbol is :  ͱ
The Symbol is :  Ͳ
The Symbol is :  ͳ
The Symbol is :  ʹ
The Symbol is :  ͵
The Symbol is :  Ͷ
The Symbol is :  ͷ
The Symbol is :  ͸
The Symbol is :  ͹
The Symbol is :  ͺ
The Symbol is :  ͻ
The Symbol is :  ͼ
The Symbol is :  ͽ
The Symbol is :  ;
The Symbol is :  Ϳ
The Symbol is :  ΀
The Symbol is :  ΁
The Symbol is :  ΂
The Symbol is :  ΃
The Symbol is :  ΄
The Symbol is :  ΅
The Symbol is :  Ά
The Symbol is :  ·
The Symbol is :  Έ
The Symbol is :  Ή
The Symbol is :  Ί
The Symbol is :  ΋
The Symbol is :  Ό
The Symbol is :  ΍
The Symbol is :  Ύ
The Symbol is :  Ώ
The Symbol is :  ΐ
The Symbol is :  Α
The Symbol is :  Β
The Symbol is :  Γ
The Symbol is :  Δ
The Symbol is :  Ε
The Symbol is :  Ζ
The Symbol is :  Η
The Symbol is :  Θ
The Symbol is :  Ι
The Symbol is :  Κ
The Symbol is :  Λ
The Symbol is :  Μ
The Symbol is :  Ν
The Symbol is :  Ξ
The Symbol is :  Ο
The Symbol is :  Π
The Symbol is :  Ρ
The Symbol is :  ΢
The Symbol is :  Σ
The Symbol is :  Τ
The Symbol is :  Υ
The Symbol is :  Φ
The Symbol is :  Χ
The Symbol is :  Ψ
The Symbol is :  Ω
The Symbol is :  Ϊ
The Symbol is :  Ϋ
The Symbol is :  ά
The Symbol is :  έ
The Symbol is :  ή
The Symbol is :  ί
The Symbol is :  ΰ
The Symbol is :  α
The Symbol is :  β
The Symbol is :  γ
The Symbol is :  δ
The Symbol is :  ε
The Symbol is :  ζ
The Symbol is :  η
The Symbol is :  θ
The Symbol is :  ι
The Symbol is :  κ
The Symbol is :  λ
The Symbol is :  μ
The Symbol is :  ν
The Symbol is :  ξ
The Symbol is :  ο
The Symbol is :  π
The Symbol is :  ρ
The Symbol is :  ς
The Symbol is :  σ
The Symbol is :  τ
The Symbol is :  υ
The Symbol is :  φ
The Symbol is :  χ
The Symbol is :  ψ
The Symbol is :  ω
The Symbol is :  ϊ
The Symbol is :  ϋ
The Symbol is :  ό
The Symbol is :  ύ
The Symbol is :  ώ
The Symbol is :  Ϗ
The Symbol is :  ϐ
The Symbol is :  ϑ
The Symbol is :  ϒ
The Symbol is :  ϓ
The Symbol is :  ϔ
The Symbol is :  ϕ
The Symbol is :  ϖ
The Symbol is :  ϗ
The Symbol is :  Ϙ
The Symbol is :  ϙ
The Symbol is :  Ϛ
The Symbol is :  ϛ
The Symbol is :  Ϝ
The Symbol is :  ϝ
The Symbol is :  Ϟ
The Symbol is :  ϟ
The Symbol is :  Ϡ
The Symbol is :  ϡ
The Symbol is :  Ϣ
The Symbol is :  ϣ
The Symbol is :  Ϥ
The Symbol is :  ϥ
The Symbol is :  Ϧ
The Symbol is :  ϧ
The Symbol is :  Ϩ
The Symbol is :  ϩ
The Symbol is :  Ϫ
The Symbol is :  ϫ
The Symbol is :  Ϭ
The Symbol is :  ϭ
The Symbol is :  Ϯ
The Symbol is :  ϯ
The Symbol is :  ϰ
The Symbol is :  ϱ
The Symbol is :  ϲ
The Symbol is :  ϳ
The Symbol is :  ϴ
The Symbol is :  ϵ
The Symbol is :  ϶
The Symbol is :  Ϸ
The Symbol is :  ϸ
The Symbol is :  Ϲ
The Symbol is :  Ϻ
The Symbol is :  ϻ
The Symbol is :  ϼ
The Symbol is :  Ͻ
The Symbol is :  Ͼ
The Symbol is :  Ͽ
*/